const FeaturedProducts = [
  {
    urlName: "ea-account",
    name: "EA Account",
    franchise: {
      urlName: "ea",
    },
    lifeCycle: null,
    releaseDate: "2023-09-19",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames: "ea account",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "fc-25",
    name: "EA SPORTS FC 25",
    franchise: {
      urlName: "ea-sports-fc",
    },
    lifeCycle: null,
    releaseDate: "2024-07-16",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames: "FC 25",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "college-football-25",
    name: "EA SPORTS™ College Football 25",
    franchise: {
      urlName: "ea-sports-college-football",
    },
    lifeCycle: null,
    releaseDate: "2024-05-16",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "EA SPORTS™ College Football 25 ; EA SPORTS College Football 25 ; college football 25 ; football 25 ,",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "madden-nfl-25",
    name: "Madden NFL 25",
    franchise: {
      urlName: "madden-nfl",
    },
    lifeCycle: null,
    releaseDate: "2024-05-16",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Madden 25 ;EA SPORTS Madden NFL 25  ; madden nfl ; Madden NFL 25  ; madden  ; madden 25  ; madden25 ; mad nfl 25 ; nfl 25  ; football  ; foot ball  ; mad 25  ; mad25 ; madden 2025",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "apex-legends",
    name: "Apex Legends",
    franchise: {
      urlName: "apex-legends",
    },
    lifeCycle: null,
    releaseDate: "2019-02-04",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Apex ;Legends ;ApexLegends ;pex ;Apex Legends ;Apex Legend ;Legend",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "fc-mobile",
    name: "EA SPORTS FC Mobile",
    franchise: {
      urlName: "ea-sports-fc",
    },
    lifeCycle: null,
    releaseDate: "2023-08-10",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "ea sports fc ; ea sports fc mobile ; fc mobile ;fc ;futbol ;soccer ;fcmobile ;fc mobile ultimate team ;fc mobile fut ;fut mobile ;fut ;futbol mobile ;soccer mobile",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "nhl-25",
    name: "NHL 25",
    franchise: {
      urlName: "nhl",
    },
    lifeCycle: null,
    releaseDate: "2024-08-22",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "nhl 25 ;hut 25 ;nhl ;hockey ;nhl25 ;nhl 25 ultimate team ;nhl25 hut ;nhl25hut ;nhl 25 hut ;hockey 25 ;hockey25 ;nhl 2025 ;nhl2025 ;hut 2025 ;hut2025 ;hockey 2025 ;hockey2025 ;nhl2025hut",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "madden-nfl-25-mobile",
    name: "Madden NFL 25 Mobile",
    franchise: {
      urlName: "madden-nfl",
    },
    lifeCycle: null,
    releaseDate: "2024-08-07",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Madden NFL Mobile ; madden nfl ; madden nfl mobile ; madden mobile; nfl mobile; nflmobile ; maddenmobile ; football ; foot ball ; madden mobile ; mutmobile ; mad ; madden 25 ; madden25 ; mad nfl 25 ; nfl 25 ; mut 25 ; madden 25 ultimate team ' football' foot ball ' mad 25; madden 2025 mobile",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "dragon-age-the-veilguard",
    name: "Dragon Age: The Veilguard",
    franchise: {
      urlName: "dragon-age",
    },
    lifeCycle: null,
    releaseDate: "2024-08-15",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames: "Dreadwolf, Dragon Age 4, DA:Dreadwolf",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "the-sims-4",
    name: "The Sims 4",
    franchise: {
      urlName: "the-sims",
    },
    lifeCycle: null,
    releaseDate: "2014-10-01",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "sims 4 ;sims4 ;ts4 ;thesims4 ;sims ;the sims 4 ;the sims4 ;thesims 4 ;thesims4 ;sim 4 ;sim4 ;thesim4 ;sim ;the sim 4 ;the sim4 ;thesim 4 ;thesim4",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "fc-24",
    name: "EA SPORTS FC 24",
    franchise: {
      urlName: "ea-sports-fc",
    },
    lifeCycle: null,
    releaseDate: "2023-07-13",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "ea sports fc ; ea sports fc 24 , fifa 24 , football club , fc 24",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "f1-24",
    name: "F1 24",
    franchise: {
      urlName: "f1",
    },
    lifeCycle: null,
    releaseDate: "2024-02-27",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "F1 24 ; F1 24 ; FI 24  ;fi 24  ; FI 2024  ; fi 24 ; f one 24 ; f 1 2024  ; f 1 24 ;formula one ; formula 1  ; form 1 24  ; formula one 24",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "zau",
    name: "Tales of Kenzera™: ZAU",
    franchise: {
      urlName: "tales-of-kenzera",
    },
    lifeCycle: null,
    releaseDate: "2023-12-08",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Tales of Kenzera™: ZAU ; Tales of Kenzera: ZAU , zau , tok , tok zau , kenzera ,",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "mysims-cozy-bundle",
    name: "MySims: Cozy Bundle",
    franchise: {
      urlName: "the-sims",
    },
    lifeCycle: null,
    releaseDate: "2024-08-27",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames: "MySims Cozy Bundle",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "madden-nfl-24",
    name: "Madden NFL 24",
    franchise: {
      urlName: "madden-nfl",
    },
    lifeCycle: null,
    releaseDate: "2023-07-12",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "madden nfl ; Madden NFL 24 , madden , madden 24 , madden24 , mad nfl 24 , nfl 24 ,  football , foot ball , mad 24 , mad24 , madden 2024",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "nhl-24",
    name: "NHL 24",
    franchise: {
      urlName: "nhl",
    },
    lifeCycle: null,
    releaseDate: "2023-08-16",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "nhl 24 ;hut 24 ;nhl ;hockey ;nhl24 ;nhl 24 ultimate team ;nhl24 hut ;nhl24hut ;nhl 24 hut ;hockey 24 ;hockey24 ;nhl 2024 ;nhl2024 ;hut 2024 ;hut2024 ;hockey 2024 ;hockey2024 ;nhl2024hut",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "plants-vs-zombies-3",
    name: "Plants vs. Zombies™ 3",
    franchise: {
      urlName: "plants-vs-zombies",
    },
    lifeCycle: null,
    releaseDate: "2024-01-17",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Plants vs. Zombies™ 3: Welcome to Zomburbia; Plants vs. Zombies 3: Welcome to Zomburbia ; plants vs. zombies 3 ;pvz  3 ;pvz 3 ;plants  3 ;zombies  3 ;plants vs zombies 3 ;plants versus zombies ;pvz ;plants ;zombies ;plants vs. zombies ;plants vs zombies ;plants  3 ;plants 3 ;zombies  3 ;zombies 3 ;zombies ;plants ;plant ;zombie ; zomburbia",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "super-mega-baseball-4",
    name: "Super Mega Baseball 4",
    franchise: {
      urlName: "super-mega-baseball",
    },
    lifeCycle: null,
    releaseDate: "2023-02-24",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "Super Mega Baseball 4 , SM baseball4 , baseball 4 , SMB4 , mega baseball 4",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "star-wars-jedi-survivor",
    name: "STAR WARS Jedi: Survivor",
    franchise: {
      urlName: "star-wars",
    },
    lifeCycle: null,
    releaseDate: "2022-12-08",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames:
      "STAR WARS Jedi: Survivor, star wars jedi , starwars jedi , jedi , jedi survivor , survivor , swj survivor , swj , swjs , starwars survivor",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
  {
    urlName: "ea-sports-pga-tour",
    name: "EA SPORTS PGA TOUR",
    franchise: {
      urlName: "ea-sports-pga-tour",
    },
    lifeCycle: null,
    releaseDate: "2023-01-06",
    platforms: null,
    productPack: "FULLGAME",
    isMobile: false,
    isSunset: false,
    altNames: "PGA Tour",
    communityContent: null,
    thumbnailExtension: "jpg",
  },
];

export default FeaturedProducts;
